# Generated by Django 6.0.3 on 2026-04-08 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="name",
            field=models.CharField(default="", max_length=150, verbose_name="Продукт"),
            preserve_default=False,
        ),
    ]
